"""add auth audit logs schema with enum and ip columns

Revision ID: 110146a9b0c5
Revises: 432f76541f06
Create Date: 2026-02-26 12:44:41.694559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '110146a9b0c5'
down_revision: Union[str, Sequence[str], None] = '432f76541f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('auth.login.success', 'auth.login.fail', 'auth.logout.success', 'auth.logout.fail', 'auth.session_refresh.success', 'auth.session_refresh.fail', 'auth.session_revoke.success', 'auth.session_revoke.fail', 'auth.signup.success', 'auth.signup.fail', 'auth.email_verify.success', 'auth.email_verify.fail', 'auth.password_change.success', 'auth.password_change.fail', 'auth.password_reset_request.success', 'auth.password_reset_request.fail', 'auth.password_reset_confirm.success', 'auth.password_reset_confirm.fail', 'auth.entra_callback.success', 'auth.entra_callback.fail', 'auth.entra_profile_fetch.success', 'auth.entra_profile_fetch.fail', name='auth_audit_event_type'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('client_ip', postgresql.INET(), nullable=True),
    sa.Column('xff_raw', sa.Text(), nullable=True),
    sa.Column('connection_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('reason_code', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('metadata IS NULL OR pg_column_size(metadata) <= 4096', name=op.f('ck_auth_audit_logs_metadata_max_4kb')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_auth_audit_logs_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_auth_audit_logs')),
    postgresql_partition_by='RANGE (occurred_at)'
    )
    op.create_index('ix_auth_audit_logs_event_type_occurred_at', 'auth_audit_logs', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_auth_audit_logs_occurred_at', 'auth_audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_auth_audit_logs_session_id_occurred_at', 'auth_audit_logs', ['session_id', 'occurred_at'], unique=False)
    op.create_index('ix_auth_audit_logs_user_id_occurred_at', 'auth_audit_logs', ['user_id', 'occurred_at'], unique=False)

    # 初期パーティションを作成する（当月 / 翌月 / 翌々月）。
    op.execute(
        """
        DO $$
        DECLARE
            base_month date := date_trunc('month', timezone('UTC', now()))::date;
            part_start date;
            part_end date;
            part_name text;
            i int;
        BEGIN
            FOR i IN 0..2 LOOP
                part_start := (base_month + make_interval(months => i))::date;
                part_end := (base_month + make_interval(months => i + 1))::date;
                part_name := format('auth_audit_logs_%s', to_char(part_start, 'YYYY_MM'));

                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF auth_audit_logs FOR VALUES FROM (%L) TO (%L)',
                    part_name,
                    part_start::timestamptz,
                    part_end::timestamptz
                );
            END LOOP;
        END
        $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_audit_logs_user_id_occurred_at', table_name='auth_audit_logs')
    op.drop_index('ix_auth_audit_logs_session_id_occurred_at', table_name='auth_audit_logs')
    op.drop_index('ix_auth_audit_logs_occurred_at', table_name='auth_audit_logs')
    op.drop_index('ix_auth_audit_logs_event_type_occurred_at', table_name='auth_audit_logs')

    # 親テーブル配下の全子パーティションを削除する。
    op.execute(
        """
        DO $$
        DECLARE
            part record;
        BEGIN
            FOR part IN
                SELECT child_ns.nspname AS schema_name, child.relname AS table_name
                FROM pg_inherits inh
                JOIN pg_class parent ON parent.oid = inh.inhparent
                JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
                JOIN pg_class child ON child.oid = inh.inhrelid
                JOIN pg_namespace child_ns ON child_ns.oid = child.relnamespace
                WHERE parent.relname = 'auth_audit_logs'
                  AND parent_ns.nspname = current_schema()
            LOOP
                EXECUTE format(
                    'DROP TABLE IF EXISTS %I.%I',
                    part.schema_name,
                    part.table_name
                );
            END LOOP;
        END
        $$;
        """
    )

    op.drop_table('auth_audit_logs')
    op.execute("DROP TYPE IF EXISTS auth_audit_event_type")
    # ### end Alembic commands ###
