"""add entra graph access token fields to sessions

Revision ID: 255fc933eb15
Revises: 42b122ca23c0
Create Date: 2026-02-25 18:49:06.266307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255fc933eb15'
down_revision: Union[str, Sequence[str], None] = '42b122ca23c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('entra_access_token', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('entra_access_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'entra_access_token_expires_at')
    op.drop_column('sessions', 'entra_access_token')
    # ### end Alembic commands ###
