"""add entra refresh token to sessions

Revision ID: 432f76541f06
Revises: 255fc933eb15
Create Date: 2026-02-25 19:01:44.734827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432f76541f06'
down_revision: Union[str, Sequence[str], None] = '255fc933eb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('entra_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'entra_refresh_token')
    # ### end Alembic commands ###
