"""init table schemas

Revision ID: 6177c957a67e
Revises: 
Create Date: 2026-03-15 16:35:10.002653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '6177c957a67e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email_normalized', name=op.f('uq_users_email_normalized')),
    schema='auth'
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False, schema='auth')
    op.create_table('auth_identities',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('email_verified_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('last_login_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identities_provider_subject'),
    schema='auth'
    )
    op.create_index('ix_auth_identities_email_normalized', 'auth_identities', ['email_normalized'], unique=False, schema='auth')
    op.create_index('ix_auth_identities_user_id', 'auth_identities', ['user_id'], unique=False, schema='auth')
    op.create_table('async_jobs',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('requested_by_user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('queue_name', sa.String(length=128), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('requested_payload', sa.NVARCHAR(), nullable=False),
    sa.Column('result_payload', sa.NVARCHAR(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('finished_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('expires_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['auth.users.id'], name=op.f('fk_async_jobs_requested_by_user_id_users'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_async_jobs')),
    schema='core'
    )
    op.create_index('ix_async_jobs_expires_at', 'async_jobs', ['expires_at'], unique=False, schema='core')
    op.create_index('ix_async_jobs_job_type_status_created_at', 'async_jobs', ['job_type', 'status', 'created_at'], unique=False, schema='core')
    op.create_index('ix_async_jobs_requested_by_user_id_created_at', 'async_jobs', ['requested_by_user_id', 'created_at'], unique=False, schema='core')
    op.create_index('ix_async_jobs_requested_by_user_id_status_job_type', 'async_jobs', ['requested_by_user_id', 'status', 'job_type'], unique=False, schema='core')
    op.create_table('email_verification_tokens',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('identity_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', mssql.DATETIME2(precision=3), nullable=False),
    sa.Column('consumed_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['auth.auth_identities.id'], name=op.f('fk_email_verification_tokens_identity_id_auth_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verification_tokens_token_hash')),
    schema='auth'
    )
    op.create_index('ix_email_verification_tokens_identity_id_consumed_at', 'email_verification_tokens', ['identity_id', 'consumed_at'], unique=False, schema='auth')
    op.create_table('password_reset_tokens',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('identity_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', mssql.DATETIME2(precision=3), nullable=False),
    sa.Column('consumed_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['auth.auth_identities.id'], name=op.f('fk_password_reset_tokens_identity_id_auth_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash')),
    schema='auth'
    )
    op.create_index('ix_password_reset_tokens_identity_id_consumed_at', 'password_reset_tokens', ['identity_id', 'consumed_at'], unique=False, schema='auth')
    op.create_table('sessions',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('auth_identity_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('entra_access_token', sa.NVARCHAR(), nullable=True),
    sa.Column('entra_refresh_token', sa.NVARCHAR(), nullable=True),
    sa.Column('entra_access_token_expires_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('expires_at', mssql.DATETIME2(precision=3), nullable=False),
    sa.Column('revoked_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['auth_identity_id'], ['auth.auth_identities.id'], name=op.f('fk_sessions_auth_identity_id_auth_identities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('session_token_hash', name=op.f('uq_sessions_session_token_hash')),
    schema='auth'
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False, schema='auth')
    op.create_index('ix_sessions_user_id_revoked_at', 'sessions', ['user_id', 'revoked_at'], unique=False, schema='auth')
    op.create_table('async_job_artifacts',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('job_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('storage_provider', sa.String(length=32), server_default=sa.text("'azure_blob'"), nullable=False),
    sa.Column('container_name', sa.String(length=128), nullable=False),
    sa.Column('blob_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('expires_at', mssql.DATETIME2(precision=3), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['core.async_jobs.id'], name=op.f('fk_async_job_artifacts_job_id_async_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_async_job_artifacts')),
    schema='core'
    )
    op.create_index('ix_async_job_artifacts_job_id_created_at', 'async_job_artifacts', ['job_id', 'created_at'], unique=False, schema='core')
    op.create_table('auth_audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(precision=3), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('session_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('xff_raw', sa.NVARCHAR(), nullable=True),
    sa.Column('connection_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('reason_code', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.NVARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth.sessions.id'], name=op.f('fk_auth_audit_logs_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_auth_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_audit_logs')),
    schema='audit'
    )
    op.create_index('ix_auth_audit_logs_event_type_occurred_at', 'auth_audit_logs', ['event_type', 'occurred_at'], unique=False, schema='audit')
    op.create_index('ix_auth_audit_logs_occurred_at', 'auth_audit_logs', ['occurred_at'], unique=False, schema='audit')
    op.create_index('ix_auth_audit_logs_session_id_occurred_at', 'auth_audit_logs', ['session_id', 'occurred_at'], unique=False, schema='audit')
    op.create_index('ix_auth_audit_logs_user_id_occurred_at', 'auth_audit_logs', ['user_id', 'occurred_at'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_audit_logs_user_id_occurred_at', table_name='auth_audit_logs', schema='audit')
    op.drop_index('ix_auth_audit_logs_session_id_occurred_at', table_name='auth_audit_logs', schema='audit')
    op.drop_index('ix_auth_audit_logs_occurred_at', table_name='auth_audit_logs', schema='audit')
    op.drop_index('ix_auth_audit_logs_event_type_occurred_at', table_name='auth_audit_logs', schema='audit')
    op.drop_table('auth_audit_logs', schema='audit')
    op.drop_index('ix_async_job_artifacts_job_id_created_at', table_name='async_job_artifacts', schema='core')
    op.drop_table('async_job_artifacts', schema='core')
    op.drop_index('ix_sessions_user_id_revoked_at', table_name='sessions', schema='auth')
    op.drop_index('ix_sessions_expires_at', table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index('ix_password_reset_tokens_identity_id_consumed_at', table_name='password_reset_tokens', schema='auth')
    op.drop_table('password_reset_tokens', schema='auth')
    op.drop_index('ix_email_verification_tokens_identity_id_consumed_at', table_name='email_verification_tokens', schema='auth')
    op.drop_table('email_verification_tokens', schema='auth')
    op.drop_index('ix_async_jobs_requested_by_user_id_status_job_type', table_name='async_jobs', schema='core')
    op.drop_index('ix_async_jobs_requested_by_user_id_created_at', table_name='async_jobs', schema='core')
    op.drop_index('ix_async_jobs_job_type_status_created_at', table_name='async_jobs', schema='core')
    op.drop_index('ix_async_jobs_expires_at', table_name='async_jobs', schema='core')
    op.drop_table('async_jobs', schema='core')
    op.drop_index('ix_auth_identities_user_id', table_name='auth_identities', schema='auth')
    op.drop_index('ix_auth_identities_email_normalized', table_name='auth_identities', schema='auth')
    op.drop_table('auth_identities', schema='auth')
    op.drop_index('ix_users_is_active', table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
