"""add async jobs and artifacts tables

Revision ID: e4f286c03b94
Revises: 110146a9b0c5
Create Date: 2026-02-28 00:41:19.137606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f286c03b94'
down_revision: Union[str, Sequence[str], None] = '110146a9b0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('auth_audit_export', name='async_job_type'), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'canceled', 'expired', name='async_job_status'), server_default='queued', nullable=False),
    sa.Column('queue_name', sa.String(length=128), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('requested_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_async_jobs_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_async_jobs'))
    )
    op.create_index('ix_async_jobs_expires_at', 'async_jobs', ['expires_at'], unique=False)
    op.create_index('ix_async_jobs_job_type_status_created_at', 'async_jobs', ['job_type', 'status', 'created_at'], unique=False)
    op.create_index('ix_async_jobs_requested_by_user_id_created_at', 'async_jobs', ['requested_by_user_id', 'created_at'], unique=False)
    op.create_table('async_job_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('auth_audit_export_file', name='async_job_artifact_type'), nullable=False),
    sa.Column('storage_provider', sa.String(length=32), server_default='azure_blob', nullable=False),
    sa.Column('container_name', sa.String(length=128), nullable=False),
    sa.Column('blob_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['async_jobs.id'], name=op.f('fk_async_job_artifacts_job_id_async_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_async_job_artifacts'))
    )
    op.create_index('ix_async_job_artifacts_expires_at', 'async_job_artifacts', ['expires_at'], unique=False)
    op.create_index('ix_async_job_artifacts_job_id_created_at', 'async_job_artifacts', ['job_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_async_job_artifacts_job_id_created_at', table_name='async_job_artifacts')
    op.drop_index('ix_async_job_artifacts_expires_at', table_name='async_job_artifacts')
    op.drop_table('async_job_artifacts')
    op.drop_index('ix_async_jobs_requested_by_user_id_created_at', table_name='async_jobs')
    op.drop_index('ix_async_jobs_job_type_status_created_at', table_name='async_jobs')
    op.drop_index('ix_async_jobs_expires_at', table_name='async_jobs')
    op.drop_table('async_jobs')
    # ### end Alembic commands ###
