{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.apiName" . }}-config
  namespace: {{ include "backend.namespace" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
