{{- $root := . -}}
{{- range $name, $job := .Values.schedulers.jobs }}
{{- if $job.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backend.schedulersName" $root }}-{{ $name | kebabcase }}
  namespace: {{ include "backend.namespace" $root }}
  labels:
    {{- include "backend.labels" $root | nindent 4 }}
    app.kubernetes.io/component: schedulers
    app.kubernetes.io/part-of: {{ $name | kebabcase }}
spec:
  schedule: {{ $job.schedule | quote }}
  suspend: {{ $job.suspend }}
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ $root.Values.schedulers.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $root.Values.schedulers.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "backend.selectorLabels" $root | nindent 12 }}
            app.kubernetes.io/component: schedulers
            app.kubernetes.io/part-of: {{ $name | kebabcase }}
            azure.workload.identity/use: "true"
          {{- with $job.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ $root.Values.serviceAccounts.schedulers.name }}
          containers:
            - name: {{ $name | kebabcase }}
              image: "{{ $root.Values.schedulers.image.repository }}:{{ $root.Values.schedulers.image.tag }}"
              imagePullPolicy: {{ $root.Values.schedulers.image.pullPolicy }}
              env:
                - name: SCHEDULERS_COMMAND
                  value: {{ $job.command | quote }}
              envFrom:
                - configMapRef:
                    name: {{ include "backend.apiName" $root }}-config
                - secretRef:
                    name: {{ $root.Values.secretRefs.name }}
              resources:
                {{- toYaml $job.resources | nindent 16 }}
---
{{- end }}
{{- end }}
