systemName: 3pull

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: cr3pulltest.azurecr.io/3pull-web
    tag: 20260303-01
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  probes:
    readiness:
      path: /
      initialDelaySeconds: 3
      periodSeconds: 10
    liveness:
      path: /
      initialDelaySeconds: 10
      periodSeconds: 15
  podAnnotations: {}
  resources: {}
