[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "argon2-cffi>=25.1.0",
    "authlib>=1.6.8",
    "fastapi>=0.131.0",
    "greenlet>=3.3.2",
    "gunicorn>=25.1.0",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "psycopg[binary]>=3.3.3",
    "pydantic-settings>=2.13.1",
    "sqlalchemy>=2.0.46",
    "structlog>=25.5.0",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.2.1",
    "uvicorn>=0.41.0",
]

[tool.uv]
package = false
