import { useMemo, useState } from 'react';
import useSWR from 'swr';
import { useTranslation } from 'react-i18next';
import { Link, useParams } from 'react-router';
import { ArrowLeft, ArrowDownToLine, Loader2 } from 'lucide-react';
import { Button } from '~/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '~/components/ui/card';
import { Input } from '~/components/ui/input';
import { Label } from '~/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '~/components/ui/select';
import { isSupportedLanguage } from '~/lib/i18n';
import {
  cancelSampleWaitBlobJob,
  createSampleWaitBlobJob,
  downloadSampleWaitBlobJob,
  getSampleWaitBlobJobs,
} from '~/lib/api-helper';

const AsyncJobSamplePage = () => {
  const { t } = useTranslation('asyncJobSample');
  const { lng } = useParams();
  const currentLanguage = lng && isSupportedLanguage(lng) ? lng : 'en';

  const [waitSeconds, setWaitSeconds] = useState(120);
  const [content, setContent] = useState('This file was generated by sample async job.');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [downloadingJobId, setDownloadingJobId] = useState<string | null>(null);
  const [cancelingJobId, setCancelingJobId] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<
    'all' | 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled' | 'expired'
  >('all');
  const [sortKey, setSortKey] = useState<'created_at' | 'finished_at'>('created_at');
  const [sortDirection, setSortDirection] = useState<'desc' | 'asc'>('desc');

  const { data, isLoading, mutate } = useSWR(
    'sample-wait-blob-jobs',
    () => getSampleWaitBlobJobs({ page: 1, pageSize: 20 }),
    {
      revalidateOnFocus: false,
      refreshInterval: 5000,
      keepPreviousData: true,
    },
  );

  const jobs = useMemo(() => data?.items ?? [], [data?.items]);
  const sortedJobs = useMemo(() => {
    const factor = sortDirection === 'asc' ? 1 : -1;
    const filtered = jobs.filter((job) => statusFilter === 'all' || job.status === statusFilter);

    return [...filtered].sort((a, b) => {
      const leftRaw = sortKey === 'finished_at' ? a.finished_at : a.created_at;
      const rightRaw = sortKey === 'finished_at' ? b.finished_at : b.created_at;
      const left = leftRaw ? new Date(leftRaw).getTime() : -Infinity;
      const right = rightRaw ? new Date(rightRaw).getTime() : -Infinity;
      if (left !== right) {
        return (left - right) * factor;
      }
      return (new Date(a.created_at).getTime() - new Date(b.created_at).getTime()) * factor;
    });
  }, [jobs, sortDirection, sortKey, statusFilter]);

  const handleCreateJob = async () => {
    try {
      setIsSubmitting(true);
      setErrorMessage(null);
      await createSampleWaitBlobJob({
        wait_seconds: waitSeconds,
        content,
      });
      await mutate();
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : t('errors.createFailed'));
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDownload = async (jobId: string) => {
    try {
      setDownloadingJobId(jobId);
      setErrorMessage(null);
      const blob = await downloadSampleWaitBlobJob(jobId);
      const objectUrl = URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = objectUrl;
      anchor.download = `${jobId}.txt`;
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
      URL.revokeObjectURL(objectUrl);
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : t('errors.downloadFailed'));
    } finally {
      setDownloadingJobId(null);
    }
  };

  const handleCancel = async (jobId: string) => {
    try {
      setCancelingJobId(jobId);
      setErrorMessage(null);
      await cancelSampleWaitBlobJob(jobId);
      await mutate();
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : t('errors.cancelFailed'));
    } finally {
      setCancelingJobId(null);
    }
  };

  return (
    <main className="container mx-auto min-h-screen max-w-6xl px-4 py-14">
      <div className="mb-8 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">{t('title')}</h1>
          <p className="mt-2 text-muted-foreground">{t('description')}</p>
        </div>
        <Button variant="outline" asChild>
          <Link to={`/${currentLanguage}`}>
            <ArrowLeft className="size-4" />
            {t('actions.backToLp')}
          </Link>
        </Button>
      </div>

      <div className="flex flex-col gap-4">
        <Card>
          <CardHeader>
            <CardTitle>{t('create.title')}</CardTitle>
            <CardDescription>{t('create.description')}</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-3 md:grid-cols-2">
            <div className="grid gap-1.5">
              <Label>{t('create.waitSeconds')}</Label>
              <Input
                type="number"
                min={1}
                max={600}
                value={waitSeconds}
                onChange={(event) => setWaitSeconds(Number(event.target.value))}
                aria-label={t('create.waitSeconds')}
              />
              <p className="text-xs text-muted-foreground">{t('create.waitSecondsHelp')}</p>
            </div>
            <div className="grid gap-1.5">
              <Label>{t('create.content')}</Label>
              <Input
                value={content}
                onChange={(event) => setContent(event.target.value)}
                aria-label={t('create.content')}
              />
              <p className="text-xs text-muted-foreground">{t('create.contentHelp')}</p>
            </div>
            <div className="md:col-span-3">
              <Button type="button" onClick={handleCreateJob} disabled={isSubmitting}>
                {isSubmitting ? <Loader2 className="size-4 animate-spin" /> : null}
                {t('actions.create')}
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>{t('history.title')}</CardTitle>
            <CardDescription>{t('history.description')}</CardDescription>
          </CardHeader>
          <CardContent className="overflow-x-auto">
            <div className="mb-4 grid gap-3 md:grid-cols-3">
              <div className="grid gap-1.5">
                <Label>{t('history.filter.statusLabel')}</Label>
                <Select
                  value={statusFilter}
                  onValueChange={(value) =>
                    setStatusFilter(
                      value as
                        | 'all'
                        | 'queued'
                        | 'running'
                        | 'succeeded'
                        | 'failed'
                        | 'canceled'
                        | 'expired',
                    )
                  }
                >
                  <SelectTrigger className="w-full sm:w-[240px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent align="start">
                    <SelectItem value="all">{t('history.filter.status.all')}</SelectItem>
                    <SelectItem value="queued">{t('history.filter.status.queued')}</SelectItem>
                    <SelectItem value="running">{t('history.filter.status.running')}</SelectItem>
                    <SelectItem value="succeeded">
                      {t('history.filter.status.succeeded')}
                    </SelectItem>
                    <SelectItem value="failed">{t('history.filter.status.failed')}</SelectItem>
                    <SelectItem value="canceled">{t('history.filter.status.canceled')}</SelectItem>
                    <SelectItem value="expired">{t('history.filter.status.expired')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-1.5">
                <Label>{t('history.sort.keyLabel')}</Label>
                <Select
                  value={sortKey}
                  onValueChange={(value) => setSortKey(value as 'created_at' | 'finished_at')}
                >
                  <SelectTrigger className="w-full sm:w-[240px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent align="start">
                    <SelectItem value="created_at">{t('history.sort.key.createdAt')}</SelectItem>
                    <SelectItem value="finished_at">{t('history.sort.key.finishedAt')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-1.5">
                <Label>{t('history.sort.directionLabel')}</Label>
                <Select
                  value={sortDirection}
                  onValueChange={(value) => setSortDirection(value as 'desc' | 'asc')}
                >
                  <SelectTrigger className="w-full sm:w-[240px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent align="start">
                    <SelectItem value="desc">{t('history.sort.direction.desc')}</SelectItem>
                    <SelectItem value="asc">{t('history.sort.direction.asc')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            {errorMessage ? <p className="mb-3 text-sm text-destructive">{errorMessage}</p> : null}
            {isLoading ? (
              <p className="text-sm text-muted-foreground">{t('states.loading')}</p>
            ) : sortedJobs.length === 0 ? (
              <p className="text-sm text-muted-foreground">{t('states.empty')}</p>
            ) : (
              <table className="min-w-full text-sm">
                <thead className="border-b text-left text-xs text-muted-foreground">
                  <tr>
                    <th className="py-2 pr-3">{t('history.columns.id')}</th>
                    <th className="py-2 pr-3">{t('history.columns.status')}</th>
                    <th className="py-2 pr-3">{t('history.columns.waitSeconds')}</th>
                    <th className="py-2 pr-3">{t('history.columns.createdAt')}</th>
                    <th className="py-2 pr-3">{t('history.columns.finishedAt')}</th>
                    <th className="py-2">{t('history.columns.actions')}</th>
                  </tr>
                </thead>
                <tbody>
                  {sortedJobs.map((job) => (
                    <tr key={job.id} className="border-b last:border-0">
                      <td className="py-2 pr-3 font-mono text-xs">{job.id}</td>
                      <td className="py-2 pr-3">{job.status}</td>
                      <td className="py-2 pr-3">{job.wait_seconds}</td>
                      <td className="py-2 pr-3">{new Date(job.created_at).toLocaleString()}</td>
                      <td className="py-2 pr-3">
                        {job.finished_at ? new Date(job.finished_at).toLocaleString() : '-'}
                      </td>
                      <td className="py-2">
                        <div className="flex items-center gap-2">
                          <Button
                            type="button"
                            size="sm"
                            variant="outline"
                            disabled={
                              job.status !== 'succeeded' ||
                              downloadingJobId === job.id ||
                              job.file_path === null
                            }
                            onClick={() => handleDownload(job.id)}
                          >
                            {downloadingJobId === job.id ? (
                              <Loader2 className="size-4 animate-spin" />
                            ) : (
                              <ArrowDownToLine className="size-4" />
                            )}
                            {t('actions.download')}
                          </Button>
                          <Button
                            type="button"
                            size="sm"
                            variant="destructive"
                            disabled={
                              !['queued', 'running'].includes(job.status) ||
                              cancelingJobId === job.id
                            }
                            onClick={() => handleCancel(job.id)}
                          >
                            {cancelingJobId === job.id ? (
                              <Loader2 className="size-4 animate-spin" />
                            ) : null}
                            {t('actions.cancel')}
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>
      </div>
    </main>
  );
};

export default AsyncJobSamplePage;
